########################################################################################

# This Makefile generated by GoMakeGen 0.6.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt all clean deps

########################################################################################

all: roller-bot

roller-bot:
	go build roller-bot.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v9
	go get -d -v pkg.re/essentialkaos/slacker.v4

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

clean:
	rm -f roller-bot

########################################################################################
